# Generated by Django 4.2.3 on 2024-08-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='lavado',
            field=models.CharField(choices=[('EXPRESS', 'Express'), ('FULL', 'Full'), ('MAQUINA', 'Máquina')], max_length=10),
        ),
    ]
