# Generated by Django 4.2.3 on 2024-08-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='patente',
            field=models.CharField(max_length=8),
        ),
    ]
