# Generated by Django 4.2.3 on 2024-08-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0002_alter_ingreso_patente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='factura',
        ),
    ]
