# Generated by Django 4.2.3 on 2024-08-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0003_remove_ingreso_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='patente',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
