# Generated by Django 4.2.3 on 2024-08-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0004_alter_ingreso_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='patente',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='propina',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
