# Generated by Django 4.2.3 on 2024-08-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0005_alter_ingreso_patente_alter_ingreso_propina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='firma_electronica',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
