# Generated by Django 4.2.3 on 2024-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0006_alter_ingreso_firma_electronica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='firma_electronica',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
