# Generated by Django 4.2.3 on 2024-08-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0007_alter_ingreso_firma_electronica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha_ingreso']},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado_factura',
            field=models.CharField(choices=[('SIN FACTURA', 'Sin Factura'), ('POR EMITIR', 'Por Emitir'), ('EMITIIDA', 'Emitida')], default='SIN FACTURA', max_length=15),
        ),
    ]
