# Generated by Django 4.2.3 on 2024-08-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0008_alter_ingreso_options_ingreso_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='comentario',
            field=models.CharField(blank=True, default='Sin Comentrio', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado_factura',
            field=models.CharField(choices=[('SIN FACTURA', 'Sin Factura'), ('POR EMITIR', 'Por Emitir'), ('EMITIDA', 'Emitida')], default='SIN FACTURA', max_length=15),
        ),
    ]
