# Generated by Django 4.2.3 on 2024-08-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0009_alter_ingreso_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='comentario',
            field=models.CharField(blank=True, default='Sin Comentario', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='propina',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
