# Generated by Django 4.2.3 on 2024-08-08 23:55

import carwash1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash1', '0010_alter_ingreso_comentario_alter_ingreso_propina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='Rut',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[carwash1.models.validar_rut_chileno]),
        ),
    ]
